config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "products#index"
  namespace :admin do
    resources :products
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
  end
    resources :products do
      member do
        post :add_to_cart
      end
    end
  resources :carts do
    collection do
      delete :clean
      post :checkout
    end

  end
  resources :cart_items
  resources :orders do
    member do
      post :pay_with_alipay
      post :pay_with_wechat
      post :apply_to_cancel 
    end
  end
  namespace :account do
    resources :orders
  end
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_is_admin
  layout "admin"
  def index
    @products = Product.all
  end
  def show
    @product = Product.find(params[:id])
  end
  def new
    @product = Product.new
  end
  def create
    @product = Product.new(product_params)
    if @product.save
    redirect_to admin_products_path, notice: "成功创建!"
    else
    render :new
    end
  end
  def edit
    @product = Product.find(params[:id])
  end
  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to admin_products_path
    else
      render :edit
    end
  end
  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to admin_products_path,alert: "你已成功删除！"
  end


  private

  def product_params
    params.require(:product).permit(:title, :description, :price, :quantity, :image)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  def index
    @products = Product.all
  end
  def show
    @product = Product.find(params[:id])
  end
  def add_to_cart
    @product = Product.find(params[:id])
    if !current_cart.products.include?(@product)
        current_cart.add_product_to_cart(@product)
        flash[:notice] = "你已成功将#{@product.title}加入购物车"
    else
      flash[:warning] = "你的购购物车内已有此物品"
    end
        redirect_to :back
  end

end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<div class="" style="padding-top:50px">
  <%= simple_form_for [:admin,@product] do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :quantity %>

    <%= f.input :image, as: :file %>
    
    <%= f.submit "Submit", data: { disable_with: "Submiting..."} %>
  <% end %>
</div>

app/views/admin/products/_productitem.html.erb
<tr>
  <td><%= product.id %></td>
  <td>
    <%= link_to product_path(product) do %>
      <% if product.image.present? %>
        <%= image_tag( product.image.thumb.url , class: "thumbnail") %>
      <% else %>
        <%= image_tag( "http://placehold.it/200x200&text=No Pic", class: "thumbnail") %>
      <% end %>
    <% end %>
  </td>
  <td><%= product.title  %></td>
  <td><%= product.price %></td>
  <td><%= link_to("Edit", edit_admin_product_path(product), class: "btn btn-info")%>
      <%= link_to("Delete", admin_product_path(product), method: :delete, data: { :confirm => "Are you sure?" },class: "btn btn-danger")%>
  </td>
</tr>

app/views/admin/products/edit.html.erb
<div class="col-md-10">
  <h3>编辑商品</h3>
  <hr>
  <div class="" style="padding-top:50px">
    <%= simple_form_for [:admin,@product] do |f| %>
      <%= f.input :title %>
      <%= f.input :description %>
      <%= f.input :price %>
      <%= f.input :quantity %>
      <% if @product.image.present? %>
        <span>目前商品图</span> <br>
        <%= image_tag(@product.image.thumb.url) %>
      <% end %>
      <%= f.input :image, as: :file %>
      <%= f.submit "Submit", data: { disable_with: "Submiting..."} %>
    <% end %>
  </div>
</div>

app/views/admin/products/index.html.erb
<div class="col-md-10">
<div class="pull-right">
  <%= link_to("上新", new_admin_product_path, class: "btn btn-primary") %>
</div>
<table class="table table-bordered ">
  <thead>
    <tr>
      <th>#</th>
      <th width="220">Product Pic</th>
      <th>名称</th>
      <th>价格</th>
      <th>管理</th>
    </tr>
  </thead>
  <tbody>
    <%= render :partial => "productitem", :collection => @products, :as => :product %>
  </tbody>
</table>
</div>

app/views/admin/products/new.html.erb
<div class="col-md-10">
  <h3>上架新品</h3>
  <hr>
  <div class="" style="padding-top:50px">
    <%= simple_form_for [:admin,@product] do |f| %>
      <%= f.input :title %>
      <%= f.input :description %>
      <%= f.input :price %>
      <%= f.input :quantity %>

      <%= f.input :image, as: :file %>

      <%= f.submit "Submit", data: { disable_with: "Submiting..."} %>
    <% end %>
  </div>
</div>